sudo: required
services:
  - docker

before_install:
  - docker build -t catherinecheatle/react-test -f ./client/Dockerfile.dev ./client
  
script:
 - docker run catherinecheatle/react-test npm test -- --coverage

after_success:
  - docker build -t catherinecheatle/multi-client ./client
  - docker build -t catherinecheatle/multi-nginx ./nginx
  - docker build -t catherinecheatle/multi-server ./server
  - docker build -t catherinecheatle/multi-worker ./worker
  #log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images to docker hub
  - docker push catherinecheatle/multi-client
  - docker push catherinecheatle/multi-nginx
  - docker push catherinecheatle/multi-server
  - docker push catherinecheatle/multi-worker
